name: Github Actions Matrix Build for Multiple Python Versions - Su Zhang

on:
  schedule:
  - cron:  '0 3 * * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7,3.8,3.9,3.11]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{matrix.python-version}}
          
      - name: install packages and dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: test with pytest
        run: |
          make test
      - name: format with black 
        run: |
          make format
